const users = require('./users/users.service.js')
const authmanagement = require('./authmanagement/authmanagement.service.js')
const mailer = require('./mailer/mailer.service.js')
const uploads = require('./uploads/uploads.service.js')
const events = require('./events/events.service.js')
const logging = require('./logging/logging.service.js')
const statistics = require('./statistics/statistics.service.js')
const categories = require('./categories/categories.service.js')
const chats = require('./chats/chats.service.js')
const chatMessages = require('./chat-messages/chat-messages.service.js')
const ads = require('./ads/ads.service.js')
const news = require('./news/news.service.js')
const statusContainers = require('./status-containers/status-containers.service.js')
const discussions = require('./discussions/discussions.service.js')
const discussionMessages = require('./discussion-messages/discussion-messages.service.js')
const groups = require('./groups/groups.service.js')
const tags = require('./tags/tags.service.js')
const violations = require('./violations/violations.service.js')
const sites = require('./sites/sites.service.js')
const preferences = require('./preferences/preferences.service.js')
const organisations = require('./organisations/organisations.service.js')
const apikeys = require('./apikeys/apikeys.service.js')
const sendstats = require('./sendstats/sendstats.service.js')
const subscribers = require('./subscribers/subscribers.service.js')
const newsletter = require('./newsletter/newsletter.service.js')
const adMessages = require('./ad-messages/ad-messages.service.js')
const statusContainerHelper = require('./status-container-helper/status-container-helper.service.js')
const translations = require('./translations/translations.service.js')

// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users)
  app.configure(authmanagement)
  app.configure(mailer)
  app.configure(uploads)
  app.configure(events)
  app.configure(logging)
  app.configure(statistics)
  app.configure(categories)
  app.configure(chats)
  app.configure(chatMessages)
  app.configure(ads)
  app.configure(news)
  app.configure(statusContainers)
  app.configure(discussions)
  app.configure(discussionMessages)
  app.configure(groups)
  app.configure(tags)
  app.configure(violations)
  app.configure(sites)
  app.configure(preferences)
  app.configure(organisations)
  app.configure(apikeys)
  app.configure(sendstats)
  app.configure(subscribers)
  app.configure(newsletter)
  app.configure(adMessages)
  app.configure(statusContainerHelper)
  app.configure(translations);
}
